apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app-pod
  template:
    metadata:
      labels:
        app: node-app-pod
    spec:
      containers:
        - name: node-app-container
          image: 192.168.3.1:5000/node-app-image
          ports:
            - containerPort: 3000
                  
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-srv
spec:
  selector:
    app: node-app-pod
  ports:
    - port: 3001
      targetPort: 3000
  type: LoadBalancer
 
